### ISSUE TITLE
Responsive navigation bar example?

### ISSUE THREAD

**Issue by wesleywesley** [ConciseCSS/concise.css#100]
Is there a good example of a responsive navigation bar?

**Comment by jameskolce** [comment]
Hi @wesleywesley, sorry for the delay! Unfortunately we don't provide a pre-made responsive navigation bar, there might be a website created with Concise with a good example but I'm unaware of it. However it should not be hard to create one depending of the pattern you choose. If you have any trouble with it you can always ask us.

**Comment by jameskolce** [comment]
Closing, if there is any problem this can be reopened.
