### ISSUE TITLE
Add a truncate class for table cells

### ISSUE THREAD

**Issue by PierBover** [ConciseCSS/concise.css#103]
This is a very common need, and it would be handy if included in ConciseCSS.

**Comment by jameskolce** [comment]
Hey @PierBover Thanks for the suggestion! Can you provide an example for this? I think I can integrate it as an add-on for the next version.

**Comment by PierBover** [comment]
Here is an example of truncating with ellipsis on a table cell:
http://jsfiddle.net/fd3Zx/5/

v4 will feature addons? That's awesome!

**Comment by jameskolce** [comment]
Great, thanks! I'll move this issue to this repository: https://github.com/ConciseCSS/concise-utils

Yeah, v4 will feature add-ons extensively, my plan is to leave the core with just normalization styles and some sort of "API" for the add-ons, which are going to provide all the functionality. In this way we can have all kinds of features without bloating the framework!

**Comment by PierBover** [comment]
Sorry I messed up...

**Comment by jameskolce** [comment]
Don't worry :) I'm going to close this issue here, moved to: https://github.com/ConciseCSS/concise-utils/issues/1

**Comment by PierBover** [comment]
Sounds awesome

How far are you from alpha?

**Comment by jameskolce** [comment]
I'm not quite sure yet, but I think it won't take a lot of time. Basically I just need to extract all the non-critical code of the framework and put it on add-ons, then clean up the core and make adjustments to provide all the necessary options for add-ons to work. I would say one month or two maybe.
I'm making all the changes here https://github.com/ConciseCSS/concise.css/tree/v4 if you want to check again in a couple of weeks!

**Comment by jameskolce** [comment]
By the way, if you want to start a project or something, go ahead! Since v4 is going to be quite different v3 will be still supported for a while.

**Comment by PierBover** [comment]
That's the reason I was asking :)

**Comment by jameskolce** [comment]
Haha yeah, I'll try to make the transition from v3 to v4 as smooth as possible though. So don't worry for that, just try to keep your styles in separated files from the framework, and you're safe.
