### ISSUE TITLE
Bordered default size button has no padding

### ISSUE THREAD

**Issue by PierBover** [ConciseCSS/concise.css#104]
This is the default size bordered button

![image](https://cloud.githubusercontent.com/assets/226483/13692346/58adc50a-e706-11e5-91ce-3ae66a9ddd9a.png)

The problem comes when using `<a>` instead of `<button>`.

`<a class="button--bordered">Nuevo colegio</a>`

Other sizes work as expected such as this extra small:

![image](https://cloud.githubusercontent.com/assets/226483/13692376/9e2bec38-e706-11e5-8218-54a57955339d.png)

`<a class="button--bordered button--xsm">Editar</a>`

**Comment by jameskolce** [comment]
`.button--bordered` is a modifier, you need to use `.button` as well: `<a class="button button--bordered">Nuevo colegio</a>`
(This behavior will be fixed in the next version)

**Comment by PierBover** [comment]
Indeed!

**Comment by jameskolce** [comment]
Great!
