### ISSUE TITLE
The examples of input--small and .input--large don't work

### ISSUE THREAD

**Issue by eolandro** [ConciseCSS/concise.css#134]
The examples of input--small and .input--large don't work in the page [here](http://concisecss.com/documentation/core/forms ). 

All inputs are always in full--width

**Comment by jameskolce** [comment]
Thanks.
Looks like a specificity issue, I'll check it out tonight.

**Comment by jameskolce** [comment]
Alright, I have fixed this. The solution is a little hacky (I used `!important`) but it shouldn't be a big problem, I'm also working in the version 4 in parallel, and it's going to be free of this issue from the beginning.

By the way, those modifiers don't change the width of the elements, but the general size, like this:

<img width="518" alt="screenshot at abr 26 11-01-30 p m" src="https://cloud.githubusercontent.com/assets/2559808/14842275/dbc58358-0c02-11e6-8dea-5bbd0cc15216.png">
