### ISSUE TITLE
The need for pxToRem function

### ISSUE THREAD

**Issue by neonnds** [ConciseCSS/concise.css#135]
```
@function pxToRem($px, $base: $font-base-size) {
  @return ($px / $base) + rem;
}
```

**Comment by jameskolce** [comment]
Thank you! I'll add it soon. Will be available in the next release.

**Comment by jameskolce** [comment]
Alright, I added the new function, it only accepts one parameter (px value). Since Rem is based in the root font-size I don't think it's useful to have a *base* parameter, however I can add it if turns out to be necessary.
