### ISSUE TITLE
IE Browser support

### ISSUE THREAD

**Issue by joshvillahermosa** [ConciseCSS/concise.css#148]
Hi, what is the lowest version of IE does this support?

**Comment by jameskolce** [comment]
Unfortunately I haven't made any tests yet, but I'd say IE11 for some features of Concise UI (e.g. dropdowns, modals) and the core should work without any problems in IE9.

**Comment by joshvillahermosa** [comment]
Okay, thank you for letting me know so quickly!

**Comment by jameskolce** [comment]
You're welcome!
