### ISSUE TITLE
Allow HTTPS via CDN

### ISSUE THREAD

**Issue by ffsantos92** [ConciseCSS/concise.css#169]
> cdn.concisecss.com uses an invalid security certificate. The certificate is only valid for the following names: *.kxcdn.com, kxcdn.com (Error code: ssl_error_bad_cert_domain)

Example: https://cdn.concisecss.com/v3.4.0/concise.css

**Comment by jameskolce** [comment]
Thanks for reporting this issue! I've added support for HTTPS and should be available in a couple of minutes.

**Comment by jameskolce** [comment]
Alright! looks like it's working, I'll close this issue.

**Comment by ffsantos92** [comment]
Yeah, it works now :-)

**Comment by jameskolce** [comment]
Great! If you find any problem with the framework or related just let me know!
