### ISSUE TITLE
Add description in Get Started/documentation explaining difference between compiled CSS and compiled CSS with UI

### ISSUE THREAD

**Issue by RTCeables** [ConciseCSS/concise.css#196]
This is a web documentation / readMe issue.

I went to download your CSS files and see you offer 3 options when clicking on the download button. The first two options are confusing. As a newbie I first wanted to know what the differences were between compiled CSS and compiled CSS with UI before I downloaded either. The only clues I could find was in the Get Started Guide Source Code table and then Table of Contents. It took some time to find and was not immediately obvious.

For us newbies please make it simpler to find the answer. May I suggest something more prominent at the top of page documenting the differences between the different download options and making reference to table of contents at the bottom.

Thanks

**Comment by jameskolce** [comment]
Thank you so much for the suggestion, and there is indeed some issues regarding how to start using Concise and I'll work on it very soon!
So basically the compiled CSS is just the basic styles with no pre-made components, and the one with UI includes all the rest of the components on top of the basic styles. In the table of contents or in the navigation menu you can see which contains what.
I'll try to add more information soon. But I hope that helps, let me know if you have any other question.

**Comment by jameskolce** [comment]
I'll close this since the next version of Concise CSS will include only one package to download, and the next version is going to be released soon.
