### ISSUE TITLE
is exist method to show modal by javascript?

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [ConciseCSS/concise.css#199]
i want control modal by javascript but i dont know how
i tried css option of modal change  `display : block` but that is not work 
if exist document i can reference about this, tell me

**Comment by jameskolce** [comment]
Yes, is possible to show the modal with Javascript, you have to set `opacity` to `1` and `pointer-events` to `all`. Let me know if that works for you!

**Comment by rkdgusrnrlrl** [comment]
oh thank!!! this is work well!!! 
i write like this
```js
function showLoginMadal() {
	$("#modal").css({ "opacity": 1 , "pointer-events" :  "all" });
}
function closeLoginMadal() {
	$("#modal").css({"opacity" : 0, "pointer-events" : "none"});
}
```
that is work well really thank you!!
hava a nice day!!!

**Comment by jameskolce** [comment]
Great, have a nice day to you! And feel free to ask anything if you have another issue with Concise!
