### ISSUE TITLE
Move SASS Functions from _globals.scss to another file

### ISSUE THREAD

**Issue by jollycic** [ConciseCSS/concise.css#241]
Hi there, thanks for this elegant framework. I am currently checking out version 4 and the new features look very promising. 

In my workflow, I usually copy `_globals.scss` to my project structure so I can override the default configuration, and then include the copy along with Concise.css source files directly from `node_modules` in my main stylesheet, like this. 
```
@import 'custom/globals'; // copy of _globals.scss
@import '../../node_modules/concise.css/concise';

/* ... project styles ... */
```
It would be nice if SASS functions were removed from `_globals.scss`, which should be purposed as a configuration file.

**Comment by jameskolce** [comment]
Hi @jollycic thank you for using Concise!

I added a sample settings file in the Documentation here: http://concisecss.com/documentation/core#settings you can just copy that for your project, it already has the functions and the `!default`s removed.

But I also think that making a settings file just to copy would be a more intuitive option. So I'll work this tonight.

Thank you for the suggestion.

**Comment by jameskolce** [comment]
Alright, there is a clean settings file now in the globals folder. the `_globals.scss` file should remain as it is since is the one used for all the add-ons.
