### ISSUE TITLE
The backlash animation spinner(with rem units)

### ISSUE THREAD

**Issue by k-ivan** [ConciseCSS/concise.css#251]
I think it's better to use pixels instead of rem units when using rem units in a circle with the animation appears backlash.

You can verify this, comment out the line
`border-right-color: transparent;`

**Comment by jameskolce** [comment]
Hi @k-ivan 
I temporarily changed the rems with px and I see the same thing. Also, commenting the property `border-right-color` has the same effect in both cases, it just becomes a full circle. So I don't quite understand the problem, could you explain more in detail the problem, perhaps a screenshot. Thanks.

**Comment by k-ivan** [comment]
Hi @jameskolce . Sorry for my English.
I recorded a video(need to take a closer look), because the screenshot does not show this moment
[https://www.youtube.com/watch?v=Qs--V4dwePE](https://www.youtube.com/watch?v=Qs--V4dwePE)
Forgot to say, I have windows10 and Google Chrome version 55.0.2883.87 m (64-bit). Same in Firefox(50.1.0).

**Comment by jameskolce** [comment]
Thank you so much for taking the work of uploading a video, I just saw what you meant. Good eye, I didn't notice it before but I'll fix it soon. Thanks!

**Comment by k-ivan** [comment]
Thank you for the quick response.

**Comment by jameskolce** [comment]
No problem 👍
