### ISSUE TITLE
_base.scss not setting font-family for input, select, textarea, or button

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#255]
You would think that setting the font-family for `:root` would apply it to all elements, but it doesn't. 

Similar to `concise.css/src/_base.scss` line around 109 we will be coping.
```scss
:root {
	box-sizing: border-box;
-->	font-family: $font-primary;
```

`concise.css/src/_base.scss` around line 412

```diff
input,
select,
textarea {
	background-color: transparent; // 1
	border-style: none; // 1
	color: inherit; // 1
++	font-family: $font-primary;
```

`concise.css/src/_base.scss` around line 446

```diff
button,
html [type="button"], // 1
[type="reset"],
[type="submit"] {
	-webkit-appearance: button; // 2
++	font-family: $font-primary;
```

**Comment by jameskolce** [comment]
Thanks! I have added `font: inherit` so it gets all the font styles from the closest definition (:root by default). Looks like that fixes the problem.
