### ISSUE TITLE
typo in src/_base.scss

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#256]
I don't believe the color being requested exists in the default `_settings.scss` file. Perhaps it does, but I could not locate it.

In `concise.css/src/_base.scss` around line 612
 
```scss
 &[disabled] {
    background-color: getColor(state, muted);
-->    color: getColor(text, ui);
    cursor: not-allowed;
  }
}
```

**Comment by jameskolce** [comment]
Thanks!
