### ISSUE TITLE
// These elements shouldn’t get a margin

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#259]
src/_base.scss around Line 696

br needs to be added to the list of elements that should be excluded from  * + * { margin-top: $block-margin; }

  // These elements shouldn’t get a margin
  br,
  li,
  kbd,
  div,
  input,
...

While IE, Chrome and Safari automatically exclude br, Firefox does not. Adding br to the list resolves the Firefox rendering bug I reported earlier.

**Comment by jameskolce** [comment]
You're right, I remember seeing this problem before and I thought I had solved it. Thanks!
