### ISSUE TITLE
concise.css/src/_print.scss recommendations

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#261]
I ended up breaking concise.css up into two different @imports

//
// Concise.css + Concise UI + Concise Utils
// --------------------------------------------------

@import 'concise.css/concise';
@import 'concise-utils/concise-utils';
@import 'concise-ui/concise-ui';

//
// Concise.css (print)
// --------------------------------------------------

@import 'concise.css/concise-print';

concise.css/src/_print.scss has several resets that don't appear necessary like resetting font sizes. The key is to set the width of the root to match the container. By default, 72dpi is assumed, so 670px is used which makes everthing look really big. Ideally we would use scale: to fix the problem, but most browsers don't have it implemented correctly. Also, browsers usually  add a margin, so your default of 2cm is likely to much. Try the following corrections:

@page { 
-- margin: 2cm; 
++ margin: 1cm; 
}
:root {
    background-color: white;
    color: black;
--  font: 12pt / 1.4 $font-print-primary;
++    width: $container-width;
}

--   h1 { font-size: 19pt; }
--   h2 { font-size: 17pt; }
--   h3 { font-size: 15pt; }
--   h4, h5, h6 {font-size: 14pt; }

  a,
  a:visited {
    color: black;
--    font-size: .57em;
    text-decoration: underline;
    word-wrap: break-word;

**Comment by jameskolce** [comment]
Thanks! This will be included in a next major version for convenience. Because we are doing a lot of changes, I see easier to take the opportunity and rework all the things for a new major version instead of dropping several minor versions and wait for a big one. When I get into that I'll let you know the details via email.

**Comment by jameskolce** [comment]
Print styles are going to be located at https://github.com/ConciseCSS/concise-print as a separate add-on. I'll add the suggested changes too.
