### ISSUE TITLE
Concise isn't compatible with postcss-input-range 3.0.1

### ISSUE THREAD

**Issue by raneio** [ConciseCSS/concise.css#274]
I made my own compiler task with gulp. It works after I downgraded postcss-input-range to 2.0.0.

```
const gulp = require('gulp')
const postcss = require('gulp-postcss')
const sass = require('gulp-sass');
const rename = require('gulp-rename')


gulp.task('concise', function () {
    return gulp.src('./sass/index.sass')
      .pipe(sass().on('error', sass.logError))
      .pipe(postcss([
        require('postcss-input-range')(),
        require('postcss-lh'),
        require('postcss-custom-media'),
        require('postcss-media-minmax'),
        require('autoprefixer'),
      ]))
      .pipe(rename('style.css'))
      .pipe(gulp.dest('./assets/'))
})
```

> Your current PostCSS version is 6.0.1, but postcss-input-range uses 5.2.17. Perhaps this is the source of the error below.
> 
> events.js:163
>       throw er; // Unhandled 'error' event
>       ^
> TypeError: selector.walkPseudos is not a function
>     at selectors.walk (/Users/me/projectX/node_modules/postcss-input-range/index.js:35:15)
>     at /Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
>     at Selector.each (/Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
>     at Selector.walk (/Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
>     at /Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:173:31
>     at Root.each (/Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
>     at Root.walk (/Users/me/projectX/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
>     at Processor.parser [as func] (/Users/me/projectX/node_modules/postcss-input-range/index.js:34:15)
>     at Processor.process (/Users/me/projectX/node_modules/postcss-selector-parser/dist/processor.js:34:14)
>     at css.walkRules (/Users/me/projectX/node_modules/postcss-input-range/index.js:57:7)

**Comment by jameskolce** [comment]
Thanks for opening the issue, I'll check this out. Or if you can send a PR I would appreciate it.

**Comment by jameskolce** [comment]
The development of the next version of concise has begun, I'll close this here.
