### ISSUE TITLE
Any plans on form styling (input, select, checkbox, ...)

### ISSUE THREAD

**Issue by pixelpeter** [ConciseCSS/concise.css#279]
I'm considering using your great framework for my next project. 
Concise + UI + Util = 39kb is a great achievement from your side.

What I'm asking myself right now is if you plan to integrate styling for/of form and form elements.

**Comment by jameskolce** [comment]
Thanks for considering Concise in your project! The core already includes some standard styling for form elements just to make them a little more appealing. There is no specific add-on for forms though.

**Comment by pixelpeter** [comment]
Thanks for the quick answer. Finally found the respective classes (dump me) ;-)

**Comment by jameskolce** [comment]
Sure, let me know if you have any other question!
