### ISSUE TITLE
flex basis and IE11

### ISSUE THREAD

**Issue by smbdelse** [ConciseCSS/concise.css#282]
When we have stacked flex items, flex child of flex parent in column flow gets 0 height in IE11, which is known bug. To prevent that behavior rather than using flex: 1 shorthand for column I propose to change it to flex: 1 1 auto.

**Comment by jameskolce** [comment]
Thanks for opening this issue! I'll get into it as soon as I can (I have been busy with other things), or you can send a pull request if you want!
