### ISSUE TITLE
Custom unit lh invalid property value with node-sass

### ISSUE THREAD

**Issue by Cronkan** [ConciseCSS/concise.css#283]
I tried setting up concise.css together with ui and util.

Installed through npm and imported into project with 
```
@import "~concise.css/concise";
@import "~concise-utils/concise-utils";
@import "~concise-ui/concise-ui";
```

Running `node-sass` with `angular-cli` for compiling scss, i get `invalid property value` on line-height. 
Inpecting a button: `line-height: 1.5lh;`

Something missing for vertical rhythm?

**Comment by jameskolce** [comment]
Hi @Cronkan 

Indeed, what you imported are just CSS files, you also need some translators for features like the `lh` unit. Concise CSS is meant to be used with the Concise CLI to compile; it includes everything you need for that, however, if you want to put things together by yourself you have to also include the following PostCSS plugins:

https://github.com/ConciseCSS/concise-cli/blob/99b0c87d109b0d42ce3ab9ba17ccac3f7a73a23a/lib/compile.js#L10-L13

They can be used from the command line in you need to, and from JS too.

Let me know if that works for you!
