### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by hansnolte** [ConciseCSS/concise.css#37]
Is Concise dead?

From the releases page - https://github.com/ConciseCSS/concise.css/releases
 v1.1.1
"We are hard at work on v2.0.0 of the framework, and are hopeful to get that released this week. "

This is now 5 weeks ago.

Please developed Concise further!!!

**Comment by pickledegg** [comment]
@steve-acet did you end up using it in your wordpress theme? I'm looking at converting a theme to use concise right now.

**Comment by steve-acet** [comment]
Hi there, sorry for the delay in getting back to you. The answer is yes, but its pretty heavily customised for my needs. There is a Concise CSS theme in development, not sure on the status, but once my current project is out of the way I will attempt to turn my theme into something usable.
