### ISSUE TITLE
Question about _lists.scss

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#50]
(please ignore/delete - noticed too late that I can post questions on Stack Exchange for Concise CSS)

**Comment by jameskolce** [comment]
About the original question:

> Wondering why you explicitly set position: relative; on the li tag in _lists.scss? ... When I commented that property everything worked and it didn't seem to break anything

You're right, seems like ``position: relative;`` doesn't have any positive effect. Will be fixed soon. Thanks.
