### ISSUE TITLE
Child columns without gutters in gutters grid

### ISSUE THREAD

**Issue by atlza** [ConciseCSS/concise.css#51]
Hi,

If you create a gutter grid with inside a nested grid.
The columns of the nested grid will have gutters to.

It'd be great to make this nested grid no guttered, adding something like a "no-gutter" class to it.
What do you think ?

Anyway, Thanks for building concise.

**Comment by keenanpayne** [comment]
@atlza 

Thank you so much for pointing this out! I never thought about nested grids unintentionally inheriting the gutter styling. I have fixed this in my latest commit and it will be bundled with the next patch release. 

If you want to nest a grid with gutters and you don't want the nested grid to have gutters, just add the `.gutters-off` class. 

Best,
Keenan
