### ISSUE TITLE
Roadmap of the framework

### ISSUE THREAD

**Issue by sachinwalia2k8** [ConciseCSS/concise.css#53]
I came across your framework and I really liked it. It's simple, concise (no pun intended :)) and extremely lightweight. I'd like to use this in a web service that we are building. However since this is a relatively new so would like to understand if you have a roadmap planned.

**Comment by keenanpayne** [comment]
@sachinwalia2k8 First off, I would like to thank you so much for posting issues about the framework as well as sharing your thoughts and ideas. It helps so much in really building a great tool for people to use. 

In regards to your question about the roadmap for Concise, I think that the goal is to create the absolute best lightweight framework that allows for easily laying out and building of user interfaces, without any opinion on design. We want to make Concise as agnostic as possible and allow for truly painless customization. 

In terms of what a particular "roadmap" would look like for this, I'm not too sure at this moment. We're still trying to optimize our codebase for the framework, and decide on what things may or may not be needed in the framework. 

As always, if you have any ideas or questions, I would love to hear them.
