### ISSUE TITLE
Sample layouts to get started

### ISSUE THREAD

**Issue by sachinwalia2k8** [ConciseCSS/concise.css#54]
I think with any new framework the best way to understand it is to see some layouts. Can you please add some sample layouts to see how different elements are structured. Maybe adapting the layouts available on getbootstrap.com for starter will be good enough.

**Comment by keenanpayne** [comment]
@sachinwalia2k8 That's a great idea! We'd talked about creating some basic layouts awhile back but it got put on the backburner for some reason. 

I'll be sure to work on a few and get them up on the website.

**Comment by keenanpayne** [comment]
I've coded a few example layouts: http://concisecss.com/get-started/examples/

I'll probably start to code more but this is a good start.
