### ISSUE TITLE
Handle multi-line columns in a grid

### ISSUE THREAD

**Issue by sachinwalia2k8** [ConciseCSS/concise.css#55]
The framework seems to be having issues with layout where combined column widths is more than 16. So in scenario as follows:

    <div class="row">
    <div class="column-4">11</div> 
    <div class="column-4">22</div> 
    <div class="column-4">33</div> 
    <div class="column-4">44</div> 
    <div class="column-4">55</div> 
    <div class="column-4">66</div> 
    </div> 

Bootstrap and Pure seems to layout it correctly by rendering the element "55" and "66" in the next line and beginning from left. However I am getting mixed results.

Can you please suggest if there is alternate way to solve this problem.

**Comment by keenanpayne** [comment]
@sachinwalia2k8 That's interesting, that's an edge case with our grid system that I'd never thought about. I'll take a look at that and get it fixed. 

Thanks!

**Comment by keenanpayne** [comment]
@sachinwalia2k8 So I've created a JSFiddle with your example code and it seems like I can't replicate your issue: http://jsfiddle.net/tdfsg0r7/1/

**Note:** I just copied/pasted all of the CSS from http://concisecss.com into this Fiddle.

**Comment by sachinwalia2k8** [comment]
It seems to be working correctly in your jsfiddle. May be there is some formatting issue in my code. Let me check. Thanks for the quick response though. I'll close the issue for now.

**Comment by keenanpayne** [comment]
Sounds good, let me know if it occurs again!

**Comment by sachinwalia2k8** [comment]
Actually I found that the issue was happening with me due to the fact that my row had columns that were of unequal heights. I tried that with bootstrap and also saw the same issue there as well. Apparently there are some hacks to solve these problems. Bootstrap provide a hack in this link: http://getbootstrap.com/css/#grid-responsive-resets. You may want to consider adding similar workaround to concisecss.

**Comment by keenanpayne** [comment]
@sachinwalia2k8 Can you please post a code example (JSFiddle, Codepen, etc) of this issue with Concise so I can check it out and commit a fix? Thanks!
