### ISSUE TITLE
Error with addon button-border with rounded and pill

### ISSUE THREAD

**Issue by atlza** [ConciseCSS/concise.css#57]
Hi there,

In the doc to make buttons rounded or pilled, it says : 
<p class="btn btn-rounded bg-red">Button</p>

That's pretty logical.

But in the addon the code is :
.btn {
  .btn-rounded { border-radius: 4px; }

  .btn-pill { border-radius: 25px; }
}

So I guess there is an error here, and the code should be :
.btn {
  &.btn-rounded { border-radius: 4px; }

  &.btn-pill { border-radius: 25px; }
}

No ?

Thanks for your work.

**Comment by keenanpayne** [comment]
@atlza Thank you for submitting! @jameskolce just pushed an update to our [add-ons](https://github.com/ConciseCSS/addons) repo so this should be fixed now.
