### ISSUE TITLE
Breakpoint issue

### ISSUE THREAD

**Issue by Ricemast** [ConciseCSS/concise.css#58]
I've found a sticking point in the grid system. At exactly 768px (the default 'small' breakpoint I believe) the grid gets stuck in a middle state and DOM elements seem to inherit styles from both ends. I find the issue when testing on an iPad mini (portrait) and replicated the issue on concisecss.com : 

![screen shot 2015-03-18 at 15 56 34](https://cloud.githubusercontent.com/assets/3462749/6713128/4e18427a-cd88-11e4-9a97-68d8536cdd10.png)

I had a look through the source but couldn't see what would be causing it. I'll happily fix it if you can point me in the right direction. 

Cheers, love the framework!

**Comment by filipelinhares** [comment]
Thanks for the report @Ricemast.

**Comment by jameskolce** [comment]
Hi @Ricemast Sorry for the delay, this issue in now fixed for concisecss.com. The problem was a conflict between JS and CSS, this has been fixed by changing ``maxWidth`` from ``768px`` to ``767px`` in the configuration object of the ``naver`` plugin`.

**Comment by Ricemast** [comment]
@jameskolce Ahh okay, I fixed the issue I was having by customising the column SCSS. Do you think there is actually an issue here or should I close?

**Comment by jameskolce** [comment]
@Ricemast Please tell me what changes you did to solve the problem, just to check if everything is okay with the framework!

**Comment by Ricemast** [comment]
@jameskolce I moved away from using the Concise column SCSS and rolled my own, so I can't comment on the stability of the framework I'm afraid!

**Comment by jameskolce** [comment]
@Ricemast I'm very sorry for any inconvenience, if you have any further issue please let us know! 

You are free to close this issue if you want, I think this is solved now. Thanks.
