### ISSUE TITLE
Create a Bower package

### ISSUE THREAD

**Issue by keenanpayne** [ConciseCSS/concise.css#6]
Should definitely create a [Bower](http://bower.io/) package to increase usage among Bower users.

**Comment by jasonszhao** [comment]
Installing Concise from Bower doesn't retrieve the package.json file required to build the project, because  package.json is on the `ignore` list in bower.json.

**Comment by jameskolce** [comment]
@jasonszhao Thanks for reporting this issue, I moved it here: https://github.com/ConciseCSS/concise.css/issues/136
