### ISSUE TITLE
Is There A Doc For Sass Development?

### ISSUE THREAD

**Issue by bobrocke** [ConciseCSS/concise.css#60]
Is there a document to describe the appropriate way to set up Concise for development with Sass in such a way that Concise updates don't overwrite changes?

**Comment by jameskolce** [comment]
Not yet, but my advice is to put all your styles in separate files like this:

At the end of **concise.scss**
```Sass
...

// Custom
@import "custom";
```

**custom.scss**
```Sass
// All my custom syles in this file
```
or
```Sass
// All my custom styles in different separated files
@import "custom/myStylesA";
@import "custom/myStylesB";
@import "custom/myStylesC";
```

To update just replace all the files except **custom.scss** or/and all the files in a ``custom`` directory.

Currently we are working in the version 3 of Concise and will use this approach.

**Comment by bobrocke** [comment]
But if I want to change a Concise Sass variable I need to do that before then end of the `concise.scss` file.

**Comment by jameskolce** [comment]
If you want to change an existing variable you can do it in the same place, for example, if you want to change something in ``_variables.scss`` you just rewrite the value. The problem with this is that you'll need to remember the files changed before to update to make a backup.

If you want to add a new variable my advice is to do it into your custom styles (custom.scss or something similar). So you can update without any problem.

The reason to add a ```custom.scss`` file at the end is to inherit all the previous styles. You can do it in another place but maybe you will have some problems, remember the way CSS works (in cascade)

Another advice for this is update manually only what you actually need. Usually there is no need to update the whole thing each time, if you website works you don't need to worry about it. When a new version is released you can check the [changelog](https://github.com/ConciseCSS/concise.css/releases) and see if there is anything you can benefit from the update.

**Comment by bobrocke** [comment]
That's not a good system. I think there needs to be a structure in which a Sass developer can work to make design customizations that will not be overwritten by a framework upgrade.

Per haps that can be a focus for a future version?

**Comment by jameskolce** [comment]
I completely agree with that, and yes, that's one of the problems we plan to solve with version 3 of the framework. But I must say that is really hard to come up with a perfect solution because the way preprocessors work today, it's really hard to make a framework perfectly upgradable and with zero redundancies at the same time, but we are working in getting the best solution possible.

**Comment by bobrocke** [comment]
A way might be for the developer to have the main .scss file call parts of Concise something like this:

```
@import the concise mix-ins
@import the concise variables

override variables as needed

@import the concise main scss

override individual styles
```
Could a system like that work?

**Comment by jameskolce** [comment]
Yes, that could work perfectly except for the styles; You will end up with redundancies since the compiler won't really override styles like it does with variables, but this might not be a serious problem depending of the size of your project. Sometimes 1kb extra isn't a big deal.

**Comment by bobrocke** [comment]
Yes, there will be a probably necessary redundancy between Concise's styles and whatever styles are overridden. Not too bad, unless someone tries to override nearly all of Concise!

**Comment by jameskolce** [comment]
Exactly and the core of the next version will be pretty small so I think this is the way to go. 
This is almost the same approach we are using with the next version, but we had not thought about the variables so thanks for the idea!
