### ISSUE TITLE
Semantic Color Names?

### ISSUE THREAD

**Issue by bobrocke** [ConciseCSS/concise.css#61]
Are there plans to move to semantic color names in future versions rather than the literal color names such a `yellow` and `green`?

Perhaps names such as `primary`, `secondary`, `link` and `warning` would be better?

**Comment by jameskolce** [comment]
Yes, we are working in the version 3 and we will have:

```Sass
$colors: (
  base: (
    "primary":   #4591aa,
    "selection": #ffd961,
    "lines":     #e0e0e0
  ),

  text: (
    "primary":   #676767,
    "secondary": #aaa
  ),

  background: (
    "dark":  #282E31,
    "light": #f5f5f5,
    "body":  #fff
  ),

  state: (
    "success": #45ca69,
    "error":   #ca4829,
    "warning":   #ffb800
  )
);
```

**Comment by bobrocke** [comment]
That's looking good. Is there a rough estimate for when v3 will be out?

**Comment by jameskolce** [comment]
That's really hard to say, but I think the next month we could have something!

**Comment by keenanpayne** [comment]
Yeah we should definitely have v3 out next month and it will be a huge update. It's been a while since an update but we believe it will be worth the wait!
