### ISSUE TITLE
v2.1?

### ISSUE THREAD

**Issue by bobrocke** [ConciseCSS/concise.css#64]
I downloaded concise.css-2.1.0.zip with expands to concise.css-2.1.0. But the bower.json file says v2.0.0? It would be helpful to have the version in a scss file, perhaps concise.scss, for certainty.

**Comment by jameskolce** [comment]
Yes, there was a mistake with the download link in ``Releases``, it doesn't include the updated bower.json but you can download the latest version here: https://github.com/ConciseCSS/concise.css/archive/master.zip 
Sorry for the inconvenience.
