### ISSUE TITLE
Updating The Responsive Mixin

### ISSUE THREAD

**Issue by KamesCG** [ConciseCSS/concise.css#65]
I find the responsive mixin somewhat limiting for more complex design, because it pretty much demands I use "min-width" as a media-query parameter.

Due to this limitation I am recommending an additional responsiveMinMax mixin, in addition to the original responsive mixin.

I think it's super important to be able to dynamically generate media-queries based on both min and max properties, without reworking the original responsive mixin.

In the responsiveMinMax mixin I reference "breakpoint-map" and the new "breakpoint-map-max" which are used in tandem to achieve more refined selectors that don't spill over into the next media-query.

```
$breakpoint-map: (
  "invisible":   0em,
  "extra-small": 30em,
  "small":       48em,
  "medium":      60em,
  "large":       70em,
  "extra-large": 80em
);

$breakpoint-map-max: (
  "invisible":   30em,
  "extra-small": 48em,
  "small":       60em,
  "medium":      70em,
  "large":       80em,
  "extra-large": 120em
);

```
Essentially, the breakpoint-map-max is used to quickly create a buffer zone for styling. 

It should be noted that the doesn't check whether the breakpoint maps exists and it simply assumes you are using them and understand it's intended consequences if the breakpoint maps aren't properly synced up.

```
@mixin responsiveMinMax($properties, $values, $responsive-values, $use-available-mixins: true, $use-max-query: true) {
  @each $property in $properties {
    @if $property == "font-size" and $use-available-mixins == true {
      #{$property}: $values;
      #{$property}: ($values / $base-font-size) * 1rem;
    } @else if $property == "line-height" and $use-available-mixins == true {
      #{$property}: ceil($values / $base-line-height) * ($base-line-height / $values);
    } @else {
      #{$property}: $values;
    }
  }// End each $property
  
  @each $breakpoint, $value in $responsive-values {
    @if $breakpoint != "null" {

    @if $use-max-query == true {
      $breakpointMin: map-get($breakpoint-map, $breakpoint);
      $breakpointMax: map-get($breakpoint-map-max, $breakpoint);
      @media (min-width: #{$breakpointMin}) and (max-width: #{$breakpointMax - 0.01em}) {
        @each $property in $properties {
          @if $property == "font-size" and $use-available-mixins == true {
            #{$property}: #{$value};
            #{$property}: ($value / $base-font-size) * 1rem;
          } @else if $property == "line-height" and $use-available-mixins == true {
            #{$property}: ceil($value / $base-line-height) * ($base-line-height / $value);
          } @else {
            #{$property}: #{$value};
          }
        }
      }
    }

    @if $use-max-query == false {
      $breakpointMin: map-get($breakpoint-map, $breakpoint);
      @media (min-width: #{$breakpointMin}){
        @each $property in $properties {
          @if $property == "font-size" and $use-available-mixins == true {
            #{$property}: #{$value};
            #{$property}: ($value / $base-font-size) * 1rem;
          } @else if $property == "line-height" and $use-available-mixins == true {
            #{$property}: ceil($value / $base-line-height) * ($base-line-height / $value);
          } @else {
            #{$property}: #{$value};
          }
        }
      }
    }

    } // End if $breakpoint
  } // End each $breakpoint
} // End @mixin responsiveFull
```

**Comment by jameskolce** [comment]
@KamesCG Could you give an example where ``min-width`` doesn't work?

Also I must say that in the v3 of Concise there won't be a ``responsive()`` mixin since it isn't strictly necessary, I replaced it with a simple and more generic ``@media #{$breakpoint}`` that works in *any* case (at least in my experience with it) and it will prevent the extra complexity that comes with this mixin. But I would like to hear your thoughts about all this, we are open to change.

**Comment by jameskolce** [comment]
Just for reference, this is an example of the new approach, it also replaces the use of ``breakpoint()`` :
```sass
.myClass {
    width: 100px;
    height: 150px;
    margin-top: 0;

    @media #{$bp-small} {
        width: 200px;
        height: 300px;
    }

    @media #{$bp-medium} {
        width: 400px;
        height: 600px;
    }
}
```

*IMHO* the syntactic sugar that you obtain with those mixins doesn't justify the complexity behind, I mean, I didn't even read the code of that mixin because is just too big and complex.

**Comment by abacaj** [comment]
@KamesCG Another engineer becoming too clever for his own good. I believe you have successfully over-engineered the responsive mixin. 

This is breaking all kinds of design principles and programming paradigms, remember to **Keep It Simple Stupid** -- http://en.wikipedia.org/wiki/KISS_principle

@jameskolce solution is simple to maintain and gets to the point quickly as a new developer can come in and modify it without spending the whole day trying to decipher what the code is doing.

**Comment by KamesCG** [comment]
I will do my best to explain why I am needing this function and why I think it's important for the ConciseCSS framework. 

Currently, I am working on a Drupal Distribution package that incorporates a lot of the ConciseCSS architecture. I was excited about Concise, because it follow the SMACSS principle, which is also used by Drupal's Omega4 responsive framework - which also has the benefit of coming with Grunt, Bower, Compass, etc... as part of the architecture.

To put it simply, we are using Drupal to manage what we are  considering stateless data using 3 different content types: Pages, Components and Items. Site administrators are able to easily manage the different types of Content without worrying what it's state will be later i.e. Accordions, Cards, Carousel, Gallery, Maps, Tabs, Showcase, etc...

I think a picture will probably be the best representation, because it's a little difficult explain fully.

![image](https://cloud.githubusercontent.com/assets/3408362/7333909/be06eda6-eb34-11e4-964d-b1603a0d8205.png)

The picture is a snapshot of how how we store data related to each Block, which contains Components and Items. Everything from responsive column settings to component state and animations are stored in the database, so it doesn't take intimate knowledge of CSS to start constructing a modern professional website using Drupal as the backbone.

In essence we let data flow freely around the Content Management System and only at the last moment before it's being output into html is the state decided using the database to retrieve the design patterns needed to structure the information.

As you might assume, this approach demands somewhat more complicated responsive design patterns, because we can't rely on the end user to know what's really happening behind the scenes, hence the more adaptable responsiveMinMax mixin.

The biggest need is being able to define a Block State in different environments ( smartphpone, laptop, etc...) without those decisions effecting a Block State higher up the media query chain.

**Comment by KamesCG** [comment]
A future goal is to have Grunt be able to connect with the Database storing these design patterns, so when you compile the CSS you are only compiling the selectors and design patterns chosen by site Administrators.

In other words when you developing a website you a have the full selection of design patterns to pick from from, but when you want to get it ready for production you can simply eliminate all the components, states, animations, colors, etc... not actually used in the final product.

My instinct was to rely heavily on multiple breakpoint maps, because that seemed like the best approach for later down the road when I wanted to be able to dynamically compile CSS. 

I could be TOTALLY wrong though and may just take the simple approach you have demonstrated.

**Comment by jameskolce** [comment]
That's a pretty AWESOME project!

For this you might want to modify the breakpoint map like this (to simplify syntax):

```Sass
$bp-extra-small = 30em
$bp-small = 48em
$bp-medium = 60em
$bp-large = 70em
$bp-extra-large = 80em
```

If I understood well your idea then this table I made could help as a reference:

Device keyword | Results in
---- | ----
Only extra-small | ``@media (max-width: #{$bp-small})``
Only small | ``@media (min-width: #{$bp-small}) and (max-width: #{$bp-medium})``
Only medium | ``@media (min-width: #{$bp-medium}) and (max-width: #{$bp-large})``
Only large | ``@media (min-width: #{$bp-large}) and (max-width: #{$bp-extra-large})``
Only extra-large | ``@media (min-width: #{$bp-extra-large})``

So the user can select a ``Device keyword`` and somehow it will compile to the data in the right side of the table. I don't know if that works for you, please let me know!

**Comment by KamesCG** [comment]
Sorry if that "TOTALLY" came off in a weird way. Didn't mean to do that at all. I like the simplified approach. The question I am not sure of yet if I will use multiple breakpoints maps for stuff like portrait mode and other device specific orientations.

I am going to put some more thought to it, because I am not quite sure how I want to handle this and could be barking up the wrong tree.

**Comment by jameskolce** [comment]
No problem, let me know if you have any further issue with the framework, I would be happy to help!
