### ISSUE TITLE
Form Labels in documentation examples do not focus inputs when clicked

### ISSUE THREAD

**Issue by mickeyvip** [ConciseCSS/concise.css#66]
The `<label>`-s in `<form>`-s do not focus the inputs when clicked.

This is due not having and `id` attribute in inputs, while having `for` attributes on `<label>`-s.

This is pretty basic functionality and it's strange it does not appear in the examples and code snippets of a Front End Framework.

Thank you

**Comment by jameskolce** [comment]
Thanks for the report, this is now fixed.

**Comment by mickeyvip** [comment]
Very cool! Thank you!
