### ISSUE TITLE
Push and pull with gutters

### ISSUE THREAD

**Issue by Dooza** [ConciseCSS/concise.css#67]
I am developing a site which is using push and pull for semantic columns. This was working fine until I was asked to change the design and have gutters in-between the columns.

The result is not good, the first column (which is actually the second column) has the gutter on the wrong side, its positioned incorrectly, and the second column (which is actually the first column) is in the wrong position.

Here are some screenshots of the problem:
![with-gutters](https://cloud.githubusercontent.com/assets/9673250/7471055/54b2dd72-f31a-11e4-95bd-955aa72593ff.png)
![without-gutters](https://cloud.githubusercontent.com/assets/9673250/7471056/54b3211a-f31a-11e4-9bca-30a2bc23a2ed.png)

I can correct this by adjusting the css but was wondering if this needed to be fixed in the framework.

Steve

**Comment by jameskolce** [comment]
It can be a problem with the framework, but I don't know if @keenanpayne wants to fix this since we are going to release the next version soon.

However, IMHO, changing the order in the HTML instead of using pull/push is a better option.

**Comment by Dooza** [comment]
Hi James,
Having semantic columns is in my mind an essential feature of any grid framework. There is a previous post about this from V1. I understand there is a new grid being used for V3, it would be great if semantic columns could stay, otherwise I might end up stripping it out and using another one that does have them.

Steve

**Comment by jameskolce** [comment]
Don't worry! atGrid.css already supports semantic columns and with it there shouldn't be any problem with the gutters.

**Comment by Dooza** [comment]
Excellent! Would it be easy to drop it into V2? I am working on a Wordpress theme which has been hacked to death, not sure I want to update it to V3 just yet.

**Comment by jameskolce** [comment]
Yes I think it would be easy, in my profile there is only the original Stylus version but I think you have access to the repo of v3 so you can get the Sass port there. If you have any problem doing that just let me know!

**Comment by Dooza** [comment]
I will give it a go and let you know how I get on.

**Comment by keenanpayne** [comment]
@Dooza Did you happen to check out the v3 grid system to see if it works for you? If not, this problem should be fixed in the next few days as we're planning on releasing v3 of the framework this week!
