### ISSUE TITLE
Provide a non trivial example file in the dist archive

### ISSUE THREAD

**Issue by Grahack** [ConciseCSS/concise.css#69]
Just an idea.

Some kind of `index.html` or `example.html` containing a bit more than what is suggested at the end of [this page](http://concisecss.com/get-started/getting-started/) would be nice. Even maybe another one with all the features that Concises has.

Thanks.

**Comment by jameskolce** [comment]
Hi @Grahack,
We are working on the next version (v3) of Concise and we already have a ``test.html`` with all the features and maybe I could make a boilerplate too. Just give us some time.
Thanks for the suggestion!

**Comment by Grahack** [comment]
Thanks for sharing Concise !
