### ISSUE TITLE
Docs column() mixin clarification

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#70]
@mixin column($column, $number-columns: $column-number, $first-column: false, $use-gutters: false, $gutter-value: strip-units($gutters))

Example from the docs : @include column(16, 4, false, true, 4);

As a non-native speaker, I find the documentation about this mixin very confusing for the first two function arguments.
$column : The number of this particular column (determines width).
$number-columns : Number of columns in the row (default is $column-number).

In the given example from the docs I would say this would mean:
"The 16th column in a row of 4 columns"

What I expected: 
$column : The total number of columns in the grid. e.g. 16
$number-columns : The column span. e.g. 4 (as in a span of 4 out of 16 columns)

**Comment by keenanpayne** [comment]
Thank you very much for pointing this out, I can see how a non-native speaker would have a difficult time understanding the documentation. I will use the revised text and update the website.
