### ISSUE TITLE
3 and 5 columns

### ISSUE THREAD

**Issue by generatepress** [ConciseCSS/concise.css#71]
Would be great if you added support for 3 and 5 columns - pretty common.

I came up with the CSS for it to use in my project - let me know if you'd like it.

Thanks!

**Comment by keenanpayne** [comment]
As for adding support, we're just getting ready to launch v3 and it's going to support 3 column grids. 

That would be great if you could share your code, I'd love to take a look at it!

**Comment by generatepress** [comment]
It's nothing special - just something I added as I'm building a WP theme using Concise.

    @media (min-width: 48em) {
	    /* 3 column grid */
	    .column-33,
	    .gutters .gutters-off .column-33 {
		    width: 33.33%;
	    }

	    .gutters .column-33 {
		    width: 31.86%;
	    }

	    .push-33 {
		    left: 33.33%;
	    }
	    .gutters .push-33 {
	    	left: 31.86%;
	    }

	    .pull-33 {
	    	right: 33.33%;
	    }
	    .gutters .pull-33 {
	    	right: 31.86%;
	    }
	
	    /* 5 column grid */
	    .column-20,
	    .gutters .gutters-off .column-20 {
	    	width: 20%;
	    }

	    .gutters .column-20 {
	    	width: 19.12%;
	    }

	    .push-20 {
		    left: 20%;
	    }
	    .gutters .push-20 {
		    left: 19.12%;
	    }

	    .pull-20 {
		    right: 20%;
	    }
	    .gutters .pull-20 {
		    right: 19.12%;
	    }
    }

Excited to see/use v3 - any timeline for release?

Thanks!

**Comment by keenanpayne** [comment]
Thanks for sharing! 

We're planning on releasing v3 next week, we're just finalizing the documentation and polishing everything up.

**Comment by generatepress** [comment]
Beautiful, looking forward to it :)
