### ISSUE TITLE
Strange Problem with Columns in Chrome

### ISSUE THREAD

**Issue by Dooza** [ConciseCSS/concise.css#72]
Just wondering if anyone has a little spare time to help me sort out a couple of problems I am having with Concise V2.

Here is my test site: http://test.aclighting.com/

Using Chrome Version 45.0.2454.85 m on Windows 7.

Issue 1.
The three columns below the slider, titled Products, Latest News and Upcoming Events, should always stay next to each other even when the browser gets smaller. It used to be fine, but I noticed today that they are not always.

For instance, slowly start making the browsers smaller. Before the first media query kicks in the end column drops down. Keep going smaller and you will notice it pops back in for a little bit before popping out again. Again this does it without the media query changing.

IE11 is fine. Firefox is ok until it gets really small, then the first column goes crazy thin and floats right.

Issue 2.
When viewed on mobile, the first column, Products, doesn't go 100%, seems to be about 50% and is floating right. If I remove overflow:hidden from the column the width problem is solved but I then get a layout issue with the H2... top padding disappearing and large margin between columns.

I have run out of ideas and I need to launch on Monday, so any help would be great :)

Steve

**Comment by Dooza** [comment]
I have cured it by applying clear:left to the row that contains the columns.

**Comment by keenanpayne** [comment]
Thanks for letting us know! Now that v3 is released feel free to post any issues that you might be having with the framework :smile:

**Comment by Dooza** [comment]
I take it support for V2 has now ended? I just launched my first site using my Wordpress Concise Theme, I was going to start making it official but I have been removed as a contributor.

**Comment by keenanpayne** [comment]
Well we could definitely still support v2, but we won't be pushing any fixes to it since we've migrated everything over to v3. 

And since I hadn't heard much from you I removed you from the team a few days ago, but if you're still interested in working on the WordPress theme, I'd be happy to add you :smile:

**Comment by Dooza** [comment]
Really sorry for not being around much this year, it's been really hectic at work. I would love to carry on helping.

I need to get my head around V3 so that I can make a new theme. I have learnt loads about WordPress this year so it shouldn't take too long.

Heading to North Wales today for a week so you won't hear from me for at least a week.
