### ISSUE TITLE
v2.x Add-ons

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#75]
I'm using v2 and I'm in the middle of the project so I'm feeling a bit reluctant to switch to v3 for this running project. Any chance I can download the v2 Add-ons somewhere?

**Comment by jameskolce** [comment]
Sure! Here you go: https://github.com/ConciseCSS/addons

**Comment by keenanpayne** [comment]
In a few minutes I'm going to remove the above repository and host all of the add-on files on our server. You will be able to access these files here: http://concisecss.com/archive/v2.0.0/add-ons/
