### ISSUE TITLE
v3.0.0 hardwired styling

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#76]
Hey,

I'm test driving v3.0.0. It requires some getting used to after v2.5. Some things are easier now, others seem a bit more complicated. What I did notice is that some components have styling hardwired, which has a good chance of needing to be overruled. E.g. the color of a modal close button. Right now it is hardcoded in _modals.scss. If you want to change it you either have to change _modals.scss or preferably overrule it in _custom.scss.

.modal-close {
  color: white;
}

Why not use color: inherit; ? 
Or not define a color at all.

Another example (a form nested in a modal, I know, I just wanted to test it). I kept wondering why my first form input field had no spacing with the next. Then I saw why:

.modal-body {
  p { margin-bottom: 0; }
  p + p { margin-bottom: unitSize(3, -4); }
}

I just want to try to avoid as much as possible overruling CSS styles. It's not Bootstrap, right ;-)

**Comment by keenanpayne** [comment]
Thanks for the comments! I'll definitely take a look at some of the things you noted and try to remove hard-coded styles where possible. Also, if you find anything else that you notice, don't hesitate to let us know!

**Comment by jameskolce** [comment]
Well, this is embarrassing... please omit those first 4 commits; I was having some late-night issues with Git.

I submitted a PR for the last one which solves this issue.
