### ISSUE TITLE
Breaking scrolling in the sidebar

### ISSUE THREAD

**Issue by naasking** [ConciseCSS/concise.css#79]
So here's an interesting one: in Chrome on Windows, if you click to open the sidebar at the top left of the alerts page (http://concisecss.com/documentation/concise-ui/alerts) but start scrolling on the wheelmouse before it's fully loaded, scrolling with the wheelmouse in the sidebar breaks. Proper scrolling isn't restored until you reload the page.

This doesn't happen on most other pages, just some of the javascript ones (like breadcrumbs, cards, etc.). It does not break in Firefox on Windows.

**Comment by jameskolce** [comment]
Interesting, give me a couple of minutes, I'll check this.

**Comment by jameskolce** [comment]
This might be an issue with Chrome (also in Linux); when you resize the window the sidebar works normally again. We are not longer touching anything related to the scrollbar as I remember, so I think this is out of our hands.

Thanks for reporting!
