### ISSUE TITLE
Package on packagist.org outdated

### ISSUE THREAD

**Issue by mrimann** [ConciseCSS/concise.css#87]
Hi

https://packagist.org/packages/concisecss/concise.css shows v2.1.0 as the latest release whereas Github shows 3.x as the latest release.

Could you maybe check this so that packagist can update the package? This in turn would make it easier to include your CSS package in a new application which consists of some packagist packages.

Cheers,
Mario

**Comment by jameskolce** [comment]
Thanks for reporting this! we will check this out.

**Comment by keenanpayne** [comment]
I've added a `composer.json` file so Packagist should update soon with the latest version of the framework.

**Comment by mrimann** [comment]
So far it didn't show up on packagist.org and I'm puzzled about the last entry in the composer.json file (replaces, see https://getcomposer.org/doc/04-schema.md#replace) which I think shouldn't be in the composer.json file.

**Comment by keenanpayne** [comment]
I'm not sure why Packagist hasn't updated yet. I have sent them an email to see if they could help resolve the issue.

**Comment by keenanpayne** [comment]
Okay, we released a new version of the framework and Packagist has been updated! https://packagist.org/packages/concisecss/concise.css
