### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by SherifRefaat** [ConciseCSS/concise.css#88]
I want to know what is the status of the RTL support?

**Comment by keenanpayne** [comment]
That's a great idea! We can definitely add RTL support and include it in our next release.

**Comment by SherifRefaat** [comment]
Do you have an idea about when the next release is going to be?
Is there any work around could be done now?

**Comment by keenanpayne** [comment]
I'm curious what specific issues you are having with designing for RTL languages? Are there specific styles or components that look bad when you use the `direction` property? (Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/direction)

**Comment by keenanpayne** [comment]
Fix has been committed, will go out in a minor release tonight.
