### ISSUE TITLE
button style consistency (low priority)

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#91]
While .button and < button > show consistency in style, < input type="submit" > doesn't.

**Comment by jameskolce** [comment]
I'll check this out, thanks!

**Comment by jameskolce** [comment]
@moonbeetle I have fixed this, soon will be released a new patch version. Meanwhile you can check the changes [here](https://github.com/jameskolce/lab-concise.css/commit/83d68e6db64add14c29061a41fae68f39af6076c) in `src/core/layout/_forms.scss
` and thanks for reporting issues with the framework!
