### ISSUE TITLE
(text) alignment and responsive layout

### ISSUE THREAD

**Issue by inseldesign** [ConciseCSS/concise.css#93]
hi there,

first of all thanks for this nice framework which is a very good starting point for different projects. i just played around and ask myself, how to handle alignment and responsive layout. If you have some code like this:

```html
<section container>
	<div row>
		<div column="3"><p>left col</p></div>
		<div column="9"><p class="text--right">right col</p></div>
	</div>
</section>
```

than responsive layout is not working any longer? same happens with floating elements. i guess i should create my custom conditional rules for that :) but thanks for a hint how to deal better with it. Thank you in advance.

**Comment by inseldesign** [comment]
Ok, after playing around this happens only when i change the fixed with for [container] as it was described in documentation.

**Comment by jameskolce** [comment]
Hi @inseldesign 
I'm not sure about understanding your question but I tested your code and the result is a responsive layout working as intended. If you put a fixed width to the container element then the responsiveness disappears. If this don't solves your question, let us know!

**Comment by jameskolce** [comment]
By the way, your example in small displays could appear like a broken layout but the behavior is as expected due the alignment of the text in the second paragraph.

**Comment by inseldesign** [comment]
Ok now i understand and solved my question. But after a few hours testing i have to say it's a very very powerful tool with less size. thanks for your quick response.

**Comment by jameskolce** [comment]
Thank you for your comments!
