### ISSUE TITLE
Disabling Responsiveness is not working

### ISSUE THREAD

**Issue by adrianmak** [ConciseCSS/concise.css#95]
I followed the instruction to remove following meta tags from head section
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">

and add
[container] { width: 1080px !important; }
in custom.scss

but it didn't work.
Div(s) are still responsiveness while resize browser windows to smaller size

desktop layout
![baidushurufa_2015-12-23_13-49-38](https://cloud.githubusercontent.com/assets/1168716/11971685/4586b8be-a97c-11e5-8ddb-bb501e25ac57.png)

resize web browser will cause div(s) responsivness 
![baidushurufa_2015-12-23_13-49-58](https://cloud.githubusercontent.com/assets/1168716/11971698/6570d9a2-a97c-11e5-83e2-ebbebac1f934.png)
![baidushurufa_2015-12-23_13-50-7](https://cloud.githubusercontent.com/assets/1168716/11971699/67c6d03a-a97c-11e5-9d7f-2dde3d22ba74.png)

**Comment by adrianmak** [comment]
While I debugging why not able to disable responsivness 

I found that the [column] css causing it to response

Take a look after resizing browser windows
![baidushurufa_2015-12-23_13-57-17](https://cloud.githubusercontent.com/assets/1168716/11971771/4e3f357a-a97d-11e5-92fc-e2a7d3887f35.png)

enlarged browser windows
 
![baidushurufa_2015-12-23_13-57-52](https://cloud.githubusercontent.com/assets/1168716/11971778/6517e814-a97d-11e5-9dc7-8ee098f22b60.png)

**Comment by jameskolce** [comment]
We are going to fix the issue and release a patch soon, meanwhile try to remove the line `95` in the file `core/utils/_atgrid.scss` if you are sure that you don't want responsiveness.
https://github.com/ConciseCSS/concise.css/blob/master/src/core/utils/_atgrid.scss#L95

Thanks!

**Comment by keenanpayne** [comment]
Alright a fix for this has been merged into master. A new release of the framework will be released this weekend including this fix.
