### ISSUE TITLE
Consider improving docs (ignore)

### ISSUE THREAD

**Issue by moonbeetle** [ConciseCSS/concise.css#98]
http://concisecss.com/documentation/core/breakpoints

Ignore my remark, at first I was puzzled about how this was different from V2.5's @ include breakpoint() but I guess in V3.3.0 it's just writing standard @ media queries and passing in the values again. Which works for me.

**Comment by jameskolce** [comment]
Yes, you write standard media queries using the breakpoint variables.
Thanks for the suggestion! we will clarify this in the docs.

**Comment by jameskolce** [comment]
I moved this to the website repo, closing.
