### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by wesleywesley** [ConciseCSS/concise.css#99]
Unless I'm missing something, I can't find a mention of browser support anywhere on the site.. Quite important though..

**Comment by jameskolce** [comment]
Thank you for reporting this! We will do some tests and publish the results soon.

**Comment by jameskolce** [comment]
Moved to the website repo, closing.

**Comment by Kaito23** [comment]
can you post a link? Can't find the supported browsers.

**Comment by jameskolce** [comment]
This issue is being handled here: https://github.com/ConciseCSS/concisecss.github.io/issues/18
But unfortunately I haven't had the chance to make the tests yet. It should work in any modern browsers but I'm not quite sure about <IE10 though.
